### ISSUE TITLE
Application crashes on HTTP 404 status code

### ISSUE THREAD

**Issue by waqary705** [DWorkS/VolleyPlus#29]
when server return HTTP status code 404 then application crashes.
 new Response.ErrorListener() {

```
                @Override
                public void onErrorResponse(VolleyError error) {
                    Log.e(TAG, "Registration Error: " + error.getMessage());
                    Toast.makeText(getApplicationContext(),
                            error.getMessage(), Toast.LENGTH_LONG).show();
                    hideDialog();
                }
            })
```

in this method and return null Toast

**Comment by jon-adams** [comment]
Could use some more context, perhaps the error log text and exactly line/call that is causing the problem or throwing the null reference exception (if that's what it's doing; you weren't clear if that is the problem or not).

But I'm assuming this is because this code is calling UI instances that may not be available anymore. When switching from background to foreground threads, always check that contexts and views are still non-null and available.
